## 1. Vector & Matrix equations

### 1.1 Length of a vector

- Vector: $\textbf{v}$ = $\left[ v_{1}, v_{2}, ..., v_{n} \right]^{T}$

- Length of a vector: || $\textbf{v}$ || =  $\sqrt{v_{1}^{2} + v_{2}^{2} + ... + v_{n}^{2}}$

In [5]:
import numpy as np
def compute_vector_length(vector):
    len_of_vector = np.sqrt(sum(vector**2))
    return len_of_vector

In [5]:
vector = np.array([-2, 4, 9, 21])
result = compute_vector_length(vector)
print(round(result, 2))

23.28


In [8]:
len_of_vector = np.linalg.norm(vector)

print(round(len_of_vector, 2))

23.28


### 1.2 Dot product

In [18]:
# Only true for vector dot product
def compute_dot_product(u, v):
    result = np.sum(u * v)
    return result    

In [15]:
v1 = np.array([0, 1, -1, 2])
v2 = np.array([2, 5, 1, 0])
result = compute_dot_product(v1, v2)

print(round(result,2))

4


In [17]:
result = np.dot(v1, v2)

print(round(result,2))

4


### 1.3 Mutiplying a vector by a matrix

In [19]:
def matrix_multi_vector(A, v):
    result = np.dot(A, v)
    return result

In [20]:
m = np.array([[-1, 1, 1], [0, -4, 9]])
v = np.array([0, 2, 1])
result = matrix_multi_vector(m, v)
print(result)

[3 1]


### 1.4 Multiplying a matrix by a matrix

In [23]:
def matrix_multi_matrix(A, B):
    result = np.dot(A, B)
    return result

In [24]:
m1 = np.array([[0, 1, 2], [2, -3, 1]])
m2 = np.array([[1, -3],[6, 1], [0, -1]])
result = matrix_multi_matrix(m1, m2)
print(result)

[[  6  -1]
 [-16 -10]]


### 1.5 Matrix Inverse

In [40]:
def inverse_matrix(A):
    det = A[0][0]*A[1][1] - A[0][1]*A[1][0]

    if det==0:
        raise(IndexError("A is uninvertible"))
    
    result = np.multiply(1/det, np.array([A[1][1], -A[0][1], -A[1][0], A[0][0]]).reshape(2, 2))
    return result

In [41]:
m1 = np.array([[-2, 6], [8, -4]])
result = inverse_matrix(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


In [42]:
result = np.linalg.inv(m1)
print(result)

[[0.1  0.15]
 [0.2  0.05]]


## 2. Eigenvecor & Eigenvalue

In [3]:
def compute_eigenvalues_eigenvectors(matrix):
    eigenvalue, eigenvector = np.linalg.eig(matrix)
    return eigenvalue, eigenvector

In [6]:
matrix = np.array([[0.9, 0.2], [0.1, 0.8]])
eigenvalues, eigenvectors = compute_eigenvalues_eigenvectors(matrix)
print(eigenvectors)

[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


## 3. Cosine Similarity

In [9]:
def compute_cosine(v1, v2):
    cos_sim = np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))
    return cos_sim

In [10]:
x = np.array([1, 2, 3, 4])
y = np.array([1, 0, 3, 0])
result = compute_cosine(x,y)
print(round(result, 3))

0.577
